services:

  # Building and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:-app}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - ${HOME}/.gitconfig:/home/ubuntu/.gitconfig
      - ${HOME}/.ssh:/home/ubuntu/.ssh
      - ${PWD}:/app
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

  # Example container with DooD and host file/net access
  app1:
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:-app2}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    
    
  # Example of running the same image with different intent
  app2:
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:-app2}
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    
